__main__ - training_phase(line:1376) - ERROR: The file trace.csv does not exist.
__main__ - training_phase(line:1377) - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:27:51 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(941) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 480
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(941) > total capcity(930)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 480
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:27:56 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1100) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 560
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1100) > total capcity(1010)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 560
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1046) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 533
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1046) > total capcity(983)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 533
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1158) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 589
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1158) > total capcity(1039)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 589
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:28:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(936) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 478
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(936) > total capcity(928)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 478
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:28:02 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1300) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 660
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1300) > total capcity(1110)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 660
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1153) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 586
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1153) > total capcity(1036)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 586
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1139) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 579
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1139) > total capcity(1029)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 579
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1134) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 577
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1134) > total capcity(1027)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 577
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:28:10 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(961) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 490
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(961) > total capcity(940)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 490
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(963) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 491
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(963) > total capcity(941)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 491
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:28:15 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-05 07:28:18 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1094) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 557
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1094) > total capcity(1007)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 557
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1056) > total capcity(900)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 538
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(1056) > total capcity(988)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 450
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 450 -> 538
