__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(712) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 366
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(712) > total capcity(666)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 366
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(693) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 356
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(693) > total capcity(656)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 356
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:31:31 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(724) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 372
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(724) > total capcity(672)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 372
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(729) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 374
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(729) > total capcity(674)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 374
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:31:34 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(606) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 313
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:31:36 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(640) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 330
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(640) > total capcity(630)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 330
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(603) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 311
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:31:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(610) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 315
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(618) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 319
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(628) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 324
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(628) > total capcity(624)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 324
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(632) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 326
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(632) > total capcity(626)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 326
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(649) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 334
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(649) > total capcity(634)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 334
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(611) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 315
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:31:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(620) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 320
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(616) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 318
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:01 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(611) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 315
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:03 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(677) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 348
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(677) > total capcity(648)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 348
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(614) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 317
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:10 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:11 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(625) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 322
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(625) > total capcity(622)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 322
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(632) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 326
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(632) > total capcity(626)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 326
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(624) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 322
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(624) > total capcity(622)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 322
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:15 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(615) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 317
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:18 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(627) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 323
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(627) > total capcity(623)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 323
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:22 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(639) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 329
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(639) > total capcity(629)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 329
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(630) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 325
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(630) > total capcity(625)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 325
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:32:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(610) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 315
