__main__ - training_phase(line:1376) - ERROR: The file trace.csv does not exist.
__main__ - training_phase(line:1377) - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:19:34 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:19:35 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(609) > total capcity(530)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 314
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(609) > total capcity(579)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 314
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(535) > total capcity(530)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 277
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:20:05 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(531) > total capcity(530)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 275
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:20:10 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(555) > total capcity(530)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 287
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(555) > total capcity(552)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 287
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(541) > total capcity(530)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 265
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 265 -> 280
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:20:30 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 23:20:33 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
