__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:40:47 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(873) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 446
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(873) > total capcity(756)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 446
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(640) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 330
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:40:51 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(667) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 343
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(667) > total capcity(653)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 343
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:40:52 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:40:55 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:40:57 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(627) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 323
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(633) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 326
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(637) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 328
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(639) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 329
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(623) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 321
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(629) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 324
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:29 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:30 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(647) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 333
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(647) > total capcity(643)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 333
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:34 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(628) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 324
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(634) > total capcity(620)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-east-1]: 310
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 310 -> 327
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:43 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 22:41:46 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
